server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.1.194:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: must-gather
      __path__: /logs/**/current.log
  pipeline_stages:
    - match:
        selector: '{job="must-gather"}'
        stages:
        - regex:
            source: filename
            expression: "/logs/.+/namespaces/(?P<namespace>.+?)/pods/(?P<pod>.+?)/(?P<container>.+?).*"
        - labels:
            namespace:
            pod:
            container:
