server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: container-logs
      __path__: /logs/sos_commands/microshift/namespaces/**/{current,previous}.log
  - targets:
      - localhost
    labels:
      job: journal
      __path__: /logs/sos_commands/logs/journalctl_--no-pager
  # journal:
  #   json: false
  #   path: /logs/sos_commands/logs/
  #   labels:
  #     job: journal
  # relabel_configs:
  #   - source_labels: ['__journal__systemd_unit']
  #     target_label: 'unit'

  pipeline_stages:
    - match:
        selector: '{job="container-logs"}'
        stages:
        - regex:
            source: filename
            expression: "/logs/sos_commands/microshift/namespaces/(?P<namespace>.+?)/pods/(?P<pod>.+?)/(?P<container>.+?)/.*"
        - labels:
            namespace:
            pod:
            container:
    - match:
        selector: '{job="journal"}'
        stages:
        - regex:
            expression: "^(?s)(?P<time>\\S+ \\S+ \\S+) (?P<host>\\S+) (?P<service>[\\w.]+)\\[(?P<pid>\\d+)\\]: (?P<message>.*)$"
        - labels:
            time:
            host:
            service:
            pid:
            message:
